name: Plugin CI

on:
  push:
    paths:
    - '.github/workflows/ci.yml'
    - 'plugin/**'
    - 'tests/**'

  schedule:
    - cron:  '0 3 * * *'


jobs:

  testing-with-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [2.7, 3.6] # these versions match the ones used in salome

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Running tests
      run: |
        cd tests
        python run_all_tests.py


  testing-in-salome:
    strategy:
      fail-fast: false
      matrix:
        salome-version: [8-3, 8-4, 8-5, 9-2, 9-3, 9-4]

    runs-on: ubuntu-18.04

    container:
      image: philbucher/ubuntu-18-04-salome-${{ matrix.salome-version }}:latest

    steps:
    - uses: actions/checkout@v1

    - name: Running tests in salome version ${{ matrix.salome-version }}
      # "--shutdown-servers=1" is not used bcs container is shut down right after
      run: |
        cd tests
        /root/salome_dir/salome -t run_all_tests.py
