name: Plugin CI

on:
  push:
    paths:
    - '.github/workflows/ci.yml'
    - 'plugin/**'
    - 'tests/**'

  schedule:
    - cron:  '0 1 * * *'

jobs:

  testing-with-python:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [2.7, 3.6] # these versions match the ones used in salome

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Running tests
      run: python tests/hello_world.py


  testing-in-salome:
    runs-on: ubuntu-18.04

    container:
      image: philbucher/salome-kratos-docker-18-04:latest

    steps:
    - uses: actions/checkout@v2-beta

    - name: Running tests in Salome
      run: run_salome_9_3 -t python tests/hello_world.py
