name: Docker Image CI

on:
  push:
    paths:
    - '.github/docker_ubuntu/DockerFile'
    - '.github/workflows/dockerimage.yml'

jobs:

  build-ubuntu-18-04:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file .github/docker_ubuntu/DockerFile --tag philbucher/salome-kratos-docker-18-04

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish the Docker image
      run: docker push philbucher/salome-kratos-docker-18-04
