name: Docker Image CI Ubuntu

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file .github/Dockerfile_ubuntu --tag my-image-name:$(date +%s)
