name: Docker Image CI

on:
  push:
    paths:
    - '.github/docker_ubuntu_bionic/DockerFile'
    - '.github/workflows/dockerimage.yml'

  schedule:
    - cron:  '0 2 * * TUE'

jobs:

  create-docker-ubuntu:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        salome-version: [8-111]

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image for salome version ${{ matrix.salome-version }}
      run: |
        if [ ${{ matrix.salome-version }} == 8-3 ]; then
          SALOME_DOWNLOAD_PATH="https://www.salome-platform.org/downloads/previous-versions/salome-v8.3.0/DownloadDistr?platform=UB16.04native&version=8.3.0"
        elif [ ${{ matrix.salome-version }} == 8-4 ]; then
          SALOME_DOWNLOAD_PATH="https://www.salome-platform.org/downloads/previous-versions/salome-v8.4.0/DownloadDistr?platform=OS1.UB16.04&version=8.4.0"
        elif [ ${{ matrix.salome-version }} == 8-5 ]; then
          SALOME_DOWNLOAD_PATH="https://www.salome-platform.org/downloads/previous-versions/salome-v8.5.0/DownloadDistr?platform=OS1.UB16.04&version=8.5.0"
        elif [ ${{ matrix.salome-version }} == 9-2 ]; then
          SALOME_DOWNLOAD_PATH="https://www.salome-platform.org/downloads/previous-versions/salome-v9.2/DownloadDistr?platform=OS1.UB18.04&version=9.2.1"
        elif [ ${{ matrix.salome-version }} == 9-3 ]; then
          SALOME_DOWNLOAD_PATH="https://www.salome-platform.org/downloads/previous-versions/salome-v9.3/DownloadDistr?platform=OS1.UB18.04&version=9.3.0"
        elif [ ${{ matrix.salome-version }} == 9-4 ]; then
          SALOME_DOWNLOAD_PATH="https://www.salome-platform.org/downloads/current-version/DownloadDistr?platform=SP.UB18.04&version=9.4.0"
        else
          exit 1
        fi

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish the Docker image for salome version ${{ matrix.salome-version }}
      run: docker push philbucher/ubuntu-18-04-salome-${{ matrix.salome-version }}
