name: Docker Image CI

on:
  push:
    paths:
    - '.github/docker_ubuntu_bionic/DockerFile'
    - '.github/workflows/dockerimage.yml'

jobs:

  create-docker-ubuntu:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        salome-version: [8-4, 8-5, 9-2, 9-3, 9-4]

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Echo salome version (${{ matrix.salome-version }})
      run: |
        if [ ${{ matrix.salome-version }} == 8-4 ]; then echo ${{ matrix.salome-version }}; fi
        if [ ${{ matrix.salome-version }} == 8-5 ]; then echo ${{ matrix.salome-version }}; fi
        if [ ${{ matrix.salome-version }} == 9-2 ]; then echo ${{ matrix.salome-version }}; fi
        if [ ${{ matrix.salome-version }} == 9-3 ]; then echo ${{ matrix.salome-version }}; fi
        if [ ${{ matrix.salome-version }} == 9-4 ]; then echo ${{ matrix.salome-version }}; fi

    - name: Build the Docker image for salome version ${{ matrix.salome-version }}
      run: docker build . --file .github/docker_ubuntu_bionic/DockerFile --tag philbucher/salome-kratos-docker-ubuntu-18-04-salome-${{ matrix.salome-version }}

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish the Docker image for salome version ${{ matrix.salome-version }}
      run: docker push philbucher/salome-kratos-docker-ubuntu-18-04-salome-${{ matrix.salome-version }}
