name: Docker Image CI Windows

on: [push]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file .github/DockerFile_windows --tag my-image-name:$(date +%s)
