name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file .github/DockerFile_ubuntu --tag philbucher/salome-kratos-docker

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish the Docker image
      run: docker push philbucher/salome-kratos-docker
